### ISSUE TITLE
P-flag placement

### ISSUE THREAD

**Issue by otroan** [ietf-6man/pio-pflag#2]
If all nodes on a link supported PD, then an on-link prefix wouldn't be needed.
In that case there would be no PIO in the RA. And if P-flag is in PIO, no P-flag.

The meaning of the P-flag has to be clarified.
Does it mean:
1) If the P-flag is set on this prefix, do not use the prefix for SLAAC if PD is supported
2) A hint that PD is available on the link

Current text seems to overload the flag for both functions, but that is not possible.
Can be rectified by keeping the flag in PIO and adding a SHOULD for all PD capable hosts to try DHCP PD, or add a P-flag also in the RA, if a hint is desired.

**Comment by furry13** [comment]
In -05 the authors updated the P flag Overview section to clarify that  P flag indicates that the network supports the pd-per-device deployment model. No more, no less.

Re: "no PIO" concern - a PIO doesn't have to be an onlink-prefix. It can contain a prefix which is not onlink (even  2001:db::/128 or ::1/128).

**Comment by ekline** [comment]
This issue seems to be interrelated with others, and addressed by recent text revisions.
