### ISSUE TITLE
Existing protocols on the link

### ISSUE THREAD

**Issue by otroan** [ietf-6man/pio-pflag#3]
E.g. mDNS advertises the interface's global address in mDNS advertisements.
With PD the host will configure the global address on a different link from the "upstream one", resulting in different behaviour. Will this break something? E.g. an application using mDNS using the global address?

**Comment by lcolitti** [comment]
I don't see a problem here. All the host's addresses in the delegated prefix are reachable from the device itself, from devices tethered behind the device, from the upstream link (through the delegating router, and via ICMPv6 redirects) and beyond the upstream link.

So if the host puts global addresses in mDNS or DNS (or any other protocol), then those addresses are as reachable as they would be if the host had addresses on the upstream link. Link-local MDNS queries and link-local addresses in MDNS on the upstream link work the same way as they do without this draft.

**Comment by ekline** [comment]
I think the host could also run a DNS-SD Proxy on behalf of some more complicated downstream arrangements, if it was important to have mDNS resolution on the delegating link.
