### ISSUE TITLE
Onlink behaviour

### ISSUE THREAD

**Issue by otroan** [ietf-6man/pio-pflag#4]
Previously hosts on the link would communicate directly. A PD host has an address that is not directly connected to the link. Meaning all traffic will have to go via the default router or there will be ICMP redirects to redirect the sending host to use the PD host directly. Should this be mentioned in the draft?

**Comment by lcolitti** [comment]
This is discussed in [section 6.4 of the pd-per-device draft](https://www.ietf.org/archive/id/draft-ietf-v6ops-dhcp-pd-per-device-08.html#name-on-link-communication).

**Comment by bobhinden** [comment]
I wonder if it would be useful to copy the text from the second paragraph of Section 6.4 from the V6OPS draft.

Some implementors may not go back and read the V6OPS draft.

**Comment by furry13** [comment]
-08 has the text copied from the v6ops draft:

https://www.ietf.org/archive/id/draft-ietf-6man-pio-pflag-08.html#name-on-link-communication

**Comment by bobhinden** [comment]
Thanks!

Bob

**Comment by ekline** [comment]
S6.4 LGTM, but it seems like there is some possible pathological scenario where two PD-per-client clients are running a lot of VMs (for example) that are talking to one another.

But having an ICMPv6 Redirect that works at the prefix level and not the /128 is definitely something to defer until it's actual problem people are having.  There are other workarounds in this case too (like distribution of routing information).

LGTM.
