### ISSUE TITLE
Address configuration state machine

### ISSUE THREAD

**Issue by otroan** [ietf-6man/pio-pflag#5]
Is a state machine needed to show how a host should configure itself?
I presume the intention of the draft is to prefer the host using PD. How much of a delay in configuring a SLAAC address should a use?

**Comment by furry13** [comment]
>Is a state machine needed to show how a host should configure itself?

Section 6.2 discusses the use of the delegated prefixes.

>I presume the intention of the draft is to prefer the host using PD. How much of a delay in configuring a SLAAC address should a use?

The draft (-06) currently says:

"If the host does not obtain any suitable prefixes via DHCPv6 PD that are suitable for SLAAC, it MAY choose to disable further processing of the P flag on that interface, allowing the host to fall back to other address assignment mechanisms, such as forming addresses via SLAAC (if the PIO has the A flag set to 1) and/or requesting individual addresses via DHCPv6."

I assume it's what you are looking for. I do not think hardcoding any specific timeouts are useful, it should be left to the implementation. The node might choose not to fallback at all.

**Comment by ekline** [comment]
Generally clear, but one chunk of text in S6.1 is worded a little bit too double/triple-negative-y, if you take my meaning:

```
                    Similarly, unless the host processes at least one
   PIO with the P bit not set, the host SHOULD NOT request individual
   IPv6 addresses from DHCPv6, i.e., it SHOULD NOT include any IA_NA or
   IA_TA options in Solicit, Renew or Rebind messages.
```

Can this be phrased in a more straightforward way?

**Comment by bobhinden** [comment]
Draft will be updated in next version.
