### ISSUE TITLE
Privacy section

### ISSUE THREAD

**Issue by otroan** [ietf-6man/pio-pflag#6]
With PD to the host, the /64 prefix uniquely identifies the host.
That has privacy implications.

One answer, which I hope we will not use, is that prefixes could be short-lived.
IPv6 addressing has to be stable, and renumbering (and much less flash renumbering) does not work well.
Documenting the change in privacy properties should be enough.

**Comment by furry13** [comment]
The current text in the Privacy Considerations section says:

"The privacy implications of implementing the P flag and using DHCPv6 PD to assign prefixes to hosts are similar to privacy implications of using DHCPv6 for assigning individual addresses. If the DHCPv6 infrastructure assigns the same prefix to the same client, then an observer might be able to identify clients based on the highest 64 bits of the client's address. Those implications and recommended countermeasures are discussed in Section 13 of [[I-D.ietf-v6ops-dhcp-pd-per-device](https://www.ietf.org/archive/id/draft-ietf-6man-pio-pflag-06.html#I-D.ietf-v6ops-dhcp-pd-per-device)].

Implementing the P flag support on a host / receiving side enables DHCPv6 on that host. Sending DHCPv6 packets may reveal some minor additional information about the host, most prominently the hostname. This is not a new concern and would apply for any network which uses DHCPv6 and sets 'M' flag in Router Advertoisements.

No privacy considerations result from supporting the P flag on the sender side."


That text seems to address your concern - at least I hope so.

**Comment by ekline** [comment]
SGTM
